name: e_book_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0 
  percent_indicator: ^3.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
 android: true
 ios: true
 image_path: "assets/app_logo.png"

    
    
                                      